// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 4 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263
// command took 1.45s and exited with 0
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263
// command took 2.51s and exited with 0
// ***** Done, took 00:00:04 (4.18 sec)   *****
// Found 4 benchmarks:
//   ContainsListInteger.LinqContains: DefaultJob
//   ContainsListInteger.PLinqContains: DefaultJob
//   ContainsListInteger.ForLoopContains: DefaultJob
//   ContainsListInteger.ForEachContains: DefaultJob

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)// **************************
// Benchmark: ContainsListInteger.LinqContains: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "ab1736b0-e8ba-4146-a91c-ca3672994263.dll" --benchmarkName "ListBenchmarks.ContainsListInteger.LinqContains" --job "Default" --benchmarkId 0 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\bin\Release\netcoreapp3.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ListBenchmarks.ContainsListInteger..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\Program.cs:line 148
   at BenchmarkDotNet.Autogenerated.Runnable_0..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 180
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 127
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 51
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: ContainsListInteger.PLinqContains: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "ab1736b0-e8ba-4146-a91c-ca3672994263.dll" --benchmarkName "ListBenchmarks.ContainsListInteger.PLinqContains" --job "Default" --benchmarkId 1 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\bin\Release\netcoreapp3.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ListBenchmarks.ContainsListInteger..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\Program.cs:line 148
   at BenchmarkDotNet.Autogenerated.Runnable_1..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 824
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 771
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 51
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: ContainsListInteger.ForLoopContains: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "ab1736b0-e8ba-4146-a91c-ca3672994263.dll" --benchmarkName "ListBenchmarks.ContainsListInteger.ForLoopContains" --job "Default" --benchmarkId 2 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\bin\Release\netcoreapp3.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ListBenchmarks.ContainsListInteger..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\Program.cs:line 148
   at BenchmarkDotNet.Autogenerated.Runnable_2..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 1468
   at BenchmarkDotNet.Autogenerated.Runnable_2.Run(IHost host, String benchmarkName) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 1415
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 51
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: ContainsListInteger.ForEachContains: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "ab1736b0-e8ba-4146-a91c-ca3672994263.dll" --benchmarkName "ListBenchmarks.ContainsListInteger.ForEachContains" --job "Default" --benchmarkId 3 in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\bin\Release\netcoreapp3.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ListBenchmarks.ContainsListInteger..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\Program.cs:line 148
   at BenchmarkDotNet.Autogenerated.Runnable_3..ctor() in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 2112
   at BenchmarkDotNet.Autogenerated.Runnable_3.Run(IHost host, String benchmarkName) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 2059
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in F:\Eduardo\Documents\Code\C#\LambdaBenchmarks\LambdaBenchmarks\bin\Release\netcoreapp3.0\ab1736b0-e8ba-4146-a91c-ca3672994263\ab1736b0-e8ba-4146-a91c-ca3672994263.notcs:line 51
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


Successfully reverted power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\ListBenchmarks.ContainsListInteger-report.csv
  BenchmarkDotNet.Artifacts\results\ListBenchmarks.ContainsListInteger-report-github.md
  BenchmarkDotNet.Artifacts\results\ListBenchmarks.ContainsListInteger-report.html

// * Detailed results *
ContainsListInteger.LinqContains: DefaultJob
Runtime = ; GC = 
There are not any results runs

ContainsListInteger.PLinqContains: DefaultJob
Runtime = ; GC = 
There are not any results runs

ContainsListInteger.ForLoopContains: DefaultJob
Runtime = ; GC = 
There are not any results runs

ContainsListInteger.ForEachContains: DefaultJob
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
AMD Ryzen 5 1600, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100
  [Host] : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT  [AttachedDebugger]


|          Method | Mean | Error |
|---------------- |-----:|------:|
|    LinqContains |   NA |    NA |
|   PLinqContains |   NA |    NA |
| ForLoopContains |   NA |    NA |
| ForEachContains |   NA |    NA |

Benchmarks with issues:
  ContainsListInteger.LinqContains: DefaultJob
  ContainsListInteger.PLinqContains: DefaultJob
  ContainsListInteger.ForLoopContains: DefaultJob
  ContainsListInteger.ForEachContains: DefaultJob

// * Warnings *
Environment
  Summary -> Benchmark was executed with attached debugger

// * Legends *
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:01 (1.3 sec), executed benchmarks: 4

Global total time: 00:00:05 (5.49 sec), executed benchmarks: 4
// * Artifacts cleanup *
